services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"

  clickhouse1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse1
    volumes:
      - ./clickhouse1/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./clickhouse1/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse1/users.xml:/etc/clickhouse-server/users.xml:ro     
      - ./data/clickhouse1:/var/lib/clickhouse
    depends_on:
      - zookeeper
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9363:9363"
    networks:
      - clicknet

  clickhouse2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse2
    volumes:
      - ./clickhouse2/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./clickhouse2/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse1/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./data/clickhouse2:/var/lib/clickhouse
    depends_on:
      - zookeeper
    ports:
      - "9001:9000"
      - "8124:8123"
      - "9364:9363"
    networks:
      - clicknet
           
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - clicknet
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456  # 登录密码
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - clicknet
      
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--collector.textfile.directory=/textfile_collector'
    volumes:
      - /home/clickhouse-cluster/node_exporter/textfile_collector:/textfile_collector:ro
    ports:
      - "9100:9100"
    networks:
      - clicknet

      

networks:
  clicknet:
    driver: bridge
volumes:
  grafana_data:
