global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clickhouse-node1'
    static_configs:
      - targets: ['clickhouse1:9363']
  - job_name: 'clickhouse-node2'
    static_configs:
      - targets: ['clickhouse2:9363']
